In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
card = pd.read_csv('UCI_Credit_Card.csv')

In [16]:
card.drop(['ID'], axis = 1, inplace = True)

In [46]:
card.shape

(30000, 24)

In [4]:
card['PAY_1'][card['PAY_1'] < 0] = 0

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [5]:
columns = ['PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6' ]
for column in columns:
    card[column][card[column] < 0] = 0

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [6]:
card['MARRIAGE'].value_counts()

2    15964
1    13659
3      323
0       54
Name: MARRIAGE, dtype: int64

In [7]:
card['MARRIAGE'][card['MARRIAGE'] == 0] = 3

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [8]:
card['EDUCATION'][card['EDUCATION'] == 5]  = 4

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [9]:
card['EDUCATION'][card['EDUCATION'] == 6]  = 4

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [10]:
card['EDUCATION'][card['EDUCATION'] == 0]  = 4

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [11]:
card['EDUCATION'].value_counts()

2    14030
1    10585
3     4917
4      468
Name: EDUCATION, dtype: int64

In [42]:
X = card.drop(['pay_def'], axis = 1)
y = card['pay_def']

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [38]:
from sklearn.metrics import classification_report, confusion_matrix

In [43]:
X_train , X_test , y_train , y_test  = train_test_split(X, y, test_size = 0.3)

In [23]:
# DecisionTree Classifier
tree_params = {"criterion": ["gini", "entropy"], "max_depth": list(range(2,4,1)), 
              "min_samples_leaf": list(range(5,7,1))}
grid_tree = GridSearchCV(DecisionTreeClassifier(), tree_params, scoring = 'f1')
grid_tree.fit(X_train, y_train)

# tree best estimator
tree_clf = grid_tree.best_estimator_

C:\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


In [24]:
y_pred = tree_clf.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.96      0.90      7082
           1       0.71      0.33      0.45      1918

   micro avg       0.83      0.83      0.83      9000
   macro avg       0.78      0.65      0.68      9000
weighted avg       0.81      0.83      0.80      9000

[[6819  263]
 [1279  639]]


In [25]:
### Applying DecisionTree after oneHotENcoding

In [26]:
from sklearn.preprocessing import OneHotEncoder

In [27]:
df = pd.DataFrame()
df['SEX'] = card['SEX']
df['MARRIAGE'] = card['MARRIAGE']
df['EDUCATION'] = card['EDUCATION']

In [28]:
onehotencoder = OneHotEncoder() 
  
df = onehotencoder.fit_transform(df).toarray() 
df

C:\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[0., 1., 1., ..., 1., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 1., 0., 0.]])

In [29]:
duplicate = pd.DataFrame(data = df)

In [31]:
new = pd.concat([card, duplicate], axis = 1)
new.drop(['SEX', 'EDUCATION', 'MARRIAGE'], axis = 1)

LIMIT_BAL  AGE  PAY_1  PAY_2  PAY_3  PAY_4  PAY_5  PAY_6  BILL_AMT1  \
0        20000.0   24      2      2      0      0      0      0     3913.0   
1       120000.0   26      0      2      0      0      0      2     2682.0   
2        90000.0   34      0      0      0      0      0      0    29239.0   
3        50000.0   37      0      0      0      0      0      0    46990.0   
4        50000.0   57      0      0      0      0      0      0     8617.0   
5        50000.0   37      0      0      0      0      0      0    64400.0   
6       500000.0   29      0      0      0      0      0      0   367965.0   
7       100000.0   23      0      0      0      0      0      0    11876.0   
8       140000.0   28      0      0      2      0      0      0    11285.0   
9        20000.0   35      0      0      0      0      0      0        0.0   
10      200000.0   34      0      0      2      0      0      0    11073.0   
11      260000.0   51      0      0      0      0      0      2    12261.0   
12      630000.0   41      0      0      0      0      0      0    12137.0   
13       70000.0   30      1      2      2      0      0      2    65802.0   
14      250000.0   29      0      0      0      0      0      0    70887.0   
15       50000.0   23      1      2      0      0      0      0    50614.0   
16       20000.0   24      0      0      2      2      2      2    15376.0   
17      320000.0   49      0      0      0      0      0      0   253286.0   
18      360000.0   49      1      0      0      0      0      0        0.0   
19      180000.0   29      1      0      0      0      0      0        0.0   
20      130000.0   39      0      0      0      0      0      0    38358.0   
21      120000.0   39      0      0      0      0      0      0      316.0   
22       70000.0   26      2      0      0      2      2      2    41087.0   
23      450000.0   40      0      0      0      0      0      0     5512.0   
24       90000.0   23      0      0      0      0      0      0     4744.0   
25       50000.0   23      0      0      0      0      0      0    47620.0   
26       60000.0   27      1      0      0      0      0      0     -109.0   
27       50000.0   30      0      0      0      0      0      0    22541.0   
28       50000.0   47      0      0      0      0      0      0      650.0   
29       50000.0   26      0      0      0      0      0      0    15329.0   
...          ...  ...    ...    ...    ...    ...    ...    ...        ...   
29970   360000.0   34      0      0      0      0      0      0    33654.0   
29971    80000.0   36      0      0      0      0      0      0    65554.0   
29972   190000.0   37      0      0      0      0      0      0    21628.0   
29973   230000.0   35      1      0      0      0      0      0        0.0   
29974    50000.0   37      1      2      2      2      0      0    10904.0   
29975   220000.0   41      0      0      0      0      0      0    45075.0   
29976    40000.0   47      2      2      3      2      2      2    52358.0   
29977   420000.0   34      0      0      0      0      0      0   131939.0   
29978   310000.0   39      0      0      0      0      0      0   238973.0   
29979   180000.0   32      0      0      0      0      0      0        0.0   
29980    50000.0   42      0      0      0      0      0      0    43998.0   
29981    50000.0   44      1      2      2      2      0      0    38671.0   
29982    90000.0   36      0      0      0      0      0      0     7752.0   
29983    20000.0   44      0      0      0      0      0      0     1822.0   
29984    30000.0   38      0      0      0      0      0      0      315.0   
29985   240000.0   30      0      0      0      0      0      0        0.0   
29986   360000.0   35      0      0      0      0      0      0     2220.0   
29987   130000.0   34      0      0      0      0      0      0    23292.0   
29988   250000.0   34      0      0      0      0      0      0   279640.0   
29989   150000.0   35      0 

In [48]:
X = new.drop(['pay_def'], axis =1)
y = new['pay_def']

In [49]:
X_train , X_test , y_train , y_test  = train_test_split(X, y, test_size = 0.3)

In [34]:
# DecisionTree Classifier
tree_params = {"criterion": ["gini", "entropy"], "max_depth": list(range(2,4,1)), 
              "min_samples_leaf": list(range(5,7,1))}
grid_tree = GridSearchCV(DecisionTreeClassifier(), tree_params, scoring = 'f1')
grid_tree.fit(X_train, y_train)

# tree best estimator
tree_clf = grid_tree.best_estimator_

C:\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


In [35]:
y_pred = tree_clf.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.95      0.89      7055
           1       0.67      0.37      0.47      1945

   micro avg       0.82      0.82      0.82      9000
   macro avg       0.76      0.66      0.68      9000
weighted avg       0.81      0.82      0.80      9000

[[6703  352]
 [1233  712]]


In [39]:
## Applying randomforest classifier

In [47]:
rvc_params = {'n_estimators' : list(range(10, 20, 1)), 'max_features' : list(range(15, 24, 1))}
grid_rvc = GridSearchCV(RandomForestClassifier(), rvc_params, scoring = 'f1')
grid_rvc.fit(X_train, y_train)

rvc = grid_rvc.best_estimator_

C:\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


In [41]:
y_pred = rvc.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.93      0.88      7055
           1       0.59      0.37      0.46      1945

   micro avg       0.81      0.81      0.81      9000
   macro avg       0.72      0.65      0.67      9000
weighted avg       0.79      0.81      0.79      9000

[[6560  495]
 [1223  722]]


In [ ]:
# Support Vector Classifier
svc_params = {'C': [ 0.7, 0.9, 1], 'kernel': ['rbf', 'poly', 'linear']}
grid_svc = GridSearchCV(SVC(), svc_params, scoring = 'f1')
grid_svc.fit(X_train, y_train)

# SVC best estimator
svc = grid_svc.best_estimator_


In [ ]:
log_reg_params = {"penalty": ['l1', 'l2'], 'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000]}
dr = LogisticRegression()
lr = GridSearchCV(dr, log_reg_params)
lr.fit(X_train, y_train)
log_reg = lr.best_estimator_